version: 2.1
     

jobs:
  Lint:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Update & install Dependencies
          command: |
            apt-get update
            echo "|||||-----||||||"
            apt-get install tidy -y
            apt-get install wget -y
            wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.22.1/hadolint-Linux-x86_64
            chmod +x hadolint
            mv hadolint /bin/hadolint
      - run:
          name: Lint HTML
          command: |
            tidy -q -e *.html
      - run:
          name: Hadolint Dockerfile
          command: |
            hadolint -v
            hadolint --ignore DL3006 Dockerfile

  Dockerize:
    machine: true
    steps:
      - checkout
      - run: |
         echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
         docker run -d --name capstone asghostknight/capstone
      - run: docker build -t asghostknight/capstone .
      - run: docker push asghostknight/capstone   


workflows:
  default:
    jobs:
      - Dockerizing:
          filters:
            branches:
              only: [master]
      
