version: 2.1
     

jobs:
  Dockerizing:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Linting HTML and Dockerfile
          command: |
            apt install tidy
            tidy -q -e *.html
            hadolint --ignore DL3006 Dockerfile

      - run:
          name: Build and Push Docker Image 
          command: |
            docker build -t asghostknight/capstone .\
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push asghostknight/capstone


workflows:
  default:
    jobs:
      - Dockerizing:
          filters:
            branches:
              only: [master]
      
