version: 2.1
     

jobs:
  Dockerizing:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Update & install Dependencies
          command: |
            apt-get update
            echo "|||||-----||||||"
            apt-get install tidy -y
            apt-get install wget -y
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.22.1/hadolint-Linux-x86_64
            
      - run:
          name: Lint HTML
          command: |
            tidy -q -e *.html
      - run:
          name: Hadolint Dockerfile
          command: |
            sudo hadolint -v
            sudo hadolint --ignore DL3006 Dockerfile
      - run:
          name: Build and Push Docker Image 
          command: |
            docker build -t asghostknight/capstone .\
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push asghostknight/capstone


workflows:
  default:
    jobs:
      - Dockerizing:
          filters:
            branches:
              only: [master]
      
